// File: pprov.v
// Generated by MyHDL 0.11
// Date: Thu Mar 23 13:13:28 2023


`timescale 1ns/10ps

module pprov (
    led,
    clock
);
// a simple LED blinks example.
// This is intended to be used with the Xula, Stickit motherboard
// and an LED  pmod board.

output led;
reg led;
input clock;

reg [24:0] cnt;
reg toggle;



always @(posedge clock) begin: PPROV_BEH
    if (($signed({1'b0, cnt}) == (32000000 - 1))) begin
        toggle <= (!toggle);
        led <= toggle;
        cnt <= 0;
    end
    else begin
        cnt <= (cnt + 1);
    end
end

endmodule
